# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/tadeze/portables/clion-2017.1.3/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/tadeze/portables/clion-2017.1.3/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tadeze/projects/iForestCodes/osu_iforest

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tadeze/projects/iForestCodes/osu_iforest

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/tadeze/portables/clion-2017.1.3/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/tadeze/portables/clion-2017.1.3/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tadeze/projects/iForestCodes/osu_iforest/CMakeFiles /home/tadeze/projects/iForestCodes/osu_iforest/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tadeze/projects/iForestCodes/osu_iforest/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named iforest

# Build rule for target.
iforest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iforest
.PHONY : iforest

# fast build rule for target.
iforest/fast:
	$(MAKE) -f CMakeFiles/iforest.dir/build.make CMakeFiles/iforest.dir/build
.PHONY : iforest/fast

#=============================================================================
# Target rules for targets named osu_iforest_doc

# Build rule for target.
osu_iforest_doc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osu_iforest_doc
.PHONY : osu_iforest_doc

# fast build rule for target.
osu_iforest_doc/fast:
	$(MAKE) -f CMakeFiles/osu_iforest_doc.dir/build.make CMakeFiles/osu_iforest_doc.dir/build
.PHONY : osu_iforest_doc/fast

#=============================================================================
# Target rules for targets named iforestlib

# Build rule for target.
iforestlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iforestlib
.PHONY : iforestlib

# fast build rule for target.
iforestlib/fast:
	$(MAKE) -f src/CMakeFiles/iforestlib.dir/build.make src/CMakeFiles/iforestlib.dir/build
.PHONY : iforestlib/fast

#=============================================================================
# Target rules for targets named Clib

# Build rule for target.
Clib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Clib
.PHONY : Clib

# fast build rule for target.
Clib/fast:
	$(MAKE) -f src/C/CMakeFiles/Clib.dir/build.make src/C/CMakeFiles/Clib.dir/build
.PHONY : Clib/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/iforest.dir/build.make CMakeFiles/iforest.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/iforest.dir/build.make CMakeFiles/iforest.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/iforest.dir/build.make CMakeFiles/iforest.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... iforest"
	@echo "... osu_iforest_doc"
	@echo "... iforestlib"
	@echo "... Clib"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

